import { RankingInterface } from "../(components)/Ranking";
import { ImageCardInterface } from "../(types)/Image";
import { PostDetailInterface } from "../(types)/post";

export const recommandImgCardMock: ImageCardInterface[] = [
    {
    postId: 1,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 5,
    createdAt: '2025-08-19',
    title: '햇살 아래 낮잠 고양이',
    catName: '루루',
    tags: ['고양이', '낮잠', '햇살'],
    likeCnt: 120,
    viewCnt: 450,
  },
  {
    postId: 2,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 3,
    createdAt: '2025-08-18',
    title: '창가에서 바라보는 세상',
    catName: '모모',
    tags: ['고양이', '창가', '풍경'],
    likeCnt: 95,
    viewCnt: 320,
  },
  {
    postId: 3,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 7,
    createdAt: '2025-08-17',
    title: '장난감과의 한판 승부',
    catName: '코코',
    tags: ['고양이', '장난감', '놀이'],
    likeCnt: 180,
    viewCnt: 600,
  },    {
    postId: 1,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 5,
    createdAt: '2025-08-19',
    title: '햇살 아래 낮잠 고양이',
    catName: '루루',
    tags: ['고양이', '낮잠', '햇살'],
    likeCnt: 120,
    viewCnt: 450,
  },
  {
    postId: 2,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 3,
    createdAt: '2025-08-18',
    title: '창가에서 바라보는 세상',
    catName: '모모',
    tags: ['고양이', '창가', '풍경'],
    likeCnt: 95,
    viewCnt: 320,
  },
  {
    postId: 3,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 7,
    createdAt: '2025-08-17',
    title: '장난감과의 한판 승부',
    catName: '코코',
    tags: ['고양이', '장난감', '놀이'],
    likeCnt: 180,
    viewCnt: 600,
  },
]


export const imageCardMock: ImageCardInterface[] = [
  {
    postId: 1,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 5,
    createdAt: '2025-08-19',
    title: '햇살 아래 낮잠 고양이',
    catName: '루루',
    tags: ['고양이', '낮잠', '햇살'],
    likeCnt: 120,
    viewCnt: 450,
  },
  {
    postId: 2,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 3,
    createdAt: '2025-08-18',
    title: '창가에서 바라보는 세상',
    catName: '모모',
    tags: ['고양이', '창가', '풍경'],
    likeCnt: 95,
    viewCnt: 320,
  },
  {
    postId: 3,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 7,
    createdAt: '2025-08-17',
    title: '장난감과의 한판 승부',
    catName: '코코',
    tags: ['고양이', '장난감', '놀이'],
    likeCnt: 180,
    viewCnt: 600,
  },
  {
    postId: 4,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 4,
    createdAt: '2025-08-16',
    title: '책상 위 탐험가',
    catName: '루비',
    tags: ['탐험', '책상', '고양이'],
    likeCnt: 75,
    viewCnt: 210,
  },
  {
    postId: 5,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 6,
    createdAt: '2025-08-15',
    title: '소파에서 느긋하게',
    catName: '치치',
    tags: ['소파', '휴식', '냥이'],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 6,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 6,
    createdAt: '2025-08-15',
    title: '최고의 고양이',
    catName: '차차',
    tags: ['냥스타그램', '귀여움', '고양이'],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 7,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 6,
    createdAt: '2025-08-15',
    title: '대단한 녀석',
    catName: '차우치',
    tags: ['대단함', '냥이', '매력'],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 8,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 6,
    createdAt: '2025-08-15',
    title: '소파',
    catName: '뮤뮤',
    tags: ['소파', '편안함', '냥이'],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 9,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 6,
    createdAt: '2025-08-15',
    title: '소파에서 느긋하게',
    catName: '치치',
    tags: ['소파', '느긋함', '고양이'],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 10,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 6,
    createdAt: '2025-08-15',
    title: '메로엠롱이',
    catName: '빠키',
    tags: ['냥이', '귀여운', '특별함'],
    likeCnt: 200,
    viewCnt: 750,
  },
];

export const floatingBtnDatasMock = [
  { name: "홈", url: "/" },
  { name: "레시피", url: "/recipe" },
  { name: "게시판", url: "/board" },
  { name: "프로필", url: "/profile" },
];

export const mockRankingData: ImageCardInterface[] = [
  {
    postId: 1,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 5,
    createdAt: '2025-08-19',
    title: '햇살 아래 낮잠 고양이',
    catName: '루루',
    tags: ['고양이', '낮잠', '햇살'],
    likeCnt: 120,
    viewCnt: 450,
  },
  {
    postId: 2,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 3,
    createdAt: '2025-08-18',
    title: '창가에서 바라보는 세상',
    catName: '모모',
    tags: ['고양이', '창가', '풍경'],
    likeCnt: 95,
    viewCnt: 320,
  },
  {
    postId: 3,
    repreImgUrl: 'https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp',
    imgCnt: 7,
    createdAt: '2025-08-17',
    title: '장난감과의 한판 승부',
    catName: '코코',
    tags: ['고양이', '장난감', '놀이'],
    likeCnt: 180,
    viewCnt: 600,
  },
];

export const postDetailMock: PostDetailInterface[] = [
  {
    postId: 1,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "햇살 아래 낮잠 고양이",
    catName: "루루",
    author: "catlover01",
    description: "따뜻한 햇살 아래에서 낮잠을 즐기는 루루의 평화로운 모습",
    tags: ["햇살", "낮잠", "귀여움"],
    likeCnt: 120,
    viewCnt: 450,
    createdAt: '2025-08-18',
  },
  {
    postId: 2,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "창가에서 바라보는 세상",
    catName: "모모",
    author: "catmom22",
    description: "창가에 앉아 세상을 구경하는 모모의 호기심 가득한 눈빛",
    tags: ["창가", "호기심", "관찰"],
    likeCnt: 95,
    viewCnt: 320,
    createdAt: '2025-08-18',
  },
  {
    postId: 3,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "장난감과의 한판 승부",
    catName: "코코",
    author: "playfulcat",
    description: "장난감 쥐를 잡기 위해 전력을 다하는 코코",
    tags: ["장난감", "사냥", "활발함"],
    likeCnt: 180,
    viewCnt: 600,
    createdAt: '2025-08-18',
  },
  {
    postId: 4,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "책상 위 탐험가",
    catName: "루비",
    author: "studycat",
    description: "책상 위를 탐험하며 새로운 세계를 발견하는 루비",
    tags: ["탐험", "책상", "모험"],
    likeCnt: 75,
    viewCnt: 210,
    createdAt: '2025-08-18',
  },
  {
    postId: 5,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "소파에서 느긋하게",
    catName: "치치",
    author: "sofacat",
    description: "소파에 누워 여유롭게 낮잠을 즐기는 치치",
    tags: ["소파", "휴식", "느긋함"],
    likeCnt: 200,
    viewCnt: 750,
    createdAt: '2025-08-18',
  },
  {
    postId: 6,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "최고의 고양이",
    catName: "차차",
    author: "bestcat",
    description: "모든 순간이 특별한 최고의 고양이 차차",
    tags: ["최고", "특별", "스타"],
    likeCnt: 200,
    viewCnt: 750,
    createdAt: '2025-08-18',
  },
  {
    postId: 7,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "대단한 녀석",
    catName: "차우치",
    author: "amazingcat",
    description: "호기심과 장난기가 가득한 대단한 고양이 차우치",
    tags: ["호기심", "장난", "대단함"],
    likeCnt: 200,
    viewCnt: 750,
    createdAt: '2025-08-18',
  },
  {
    postId: 8,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "소파",
    catName: "뮤뮤",
    author: "simplecat",
    description: "심플하게 소파에서 편안히 쉬는 뮤뮤",
    tags: ["소파", "심플", "휴식"],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 9,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "소파에서 느긋하게",
    catName: "치치",
    author: "sofacat2",
    description: "또 다른 순간의 치치, 소파는 역시 최고",
    tags: ["소파", "치치", "휴식"],
    likeCnt: 200,
    viewCnt: 750,
  },
  {
    postId: 10,
    images: [
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
      "https://res.cloudinary.com/dir5rw15x/image/upload/v1745686365/mflsfsiy6pqasbrvynv4.webp",
    ],
    title: "메로엠롱이",
    catName: "빠키",
    author: "uniqueowner",
    description: "독특한 매력을 가진 고양이 빠키의 일상",
    tags: ["독특", "매력", "일상"],
    likeCnt: 200,
    viewCnt: 750,
  },
];
